import { Hero } from "./hero";

export const HEROES: Hero[] = [
    { _id: 11, _name: 'Dr Nice', _saying: 'I'+'m a boss!'},
    { _id: 12, _name: 'Narco', _saying: 'I'+ 'm a boss!' },
    { _id: 13, _name: 'Bombasto', _saying: 'I'+ 'm a boss!' },
    { _id: 14, _name: 'Celeritas' , _saying: 'I'+ 'm a boss!' },
    { _id: 15, _name: 'Magneta' , _saying: 'I'+ 'm a boss!'  },
    { _id: 16, _name: 'RubberMan' , _saying: 'I'+ 'm a boss!'},
    { _id: 17, _name: 'Dynama' , _saying: 'I'+ 'm a boss!' },
    { _id: 18, _name: 'Dr IQ' , _saying: 'I'+ 'm a boss!' },
    { _id: 19, _name: 'Magma', _saying: 'I'+ 'm a boss!' },
    { _id: 20, _name: 'Tornado' , _saying: 'I'+ 'm a boss!' },
    { _id: 1, _name: 'Dr Nice', _saying: 'I'+'m a boss!'},
    { _id: 2, _name: 'Narco', _saying: 'I'+ 'm a boss!' },
    { _id: 3, _name: 'Bombasto', _saying: 'I'+ 'm a boss!' },
    { _id: 4, _name: 'Celeritas' , _saying: 'I'+ 'm a boss!' },
    { _id: 5, _name: 'Magneta' , _saying: 'I'+ 'm a boss!'  },
    { _id: 6, _name: 'RubberMan' , _saying: 'I'+ 'm a boss!'},
    { _id: 7, _name: 'Dynama' , _saying: 'I'+ 'm a boss!' },
    { _id: 8, _name: 'Dr IQ' , _saying: 'I'+ 'm a boss!' },
    { _id: 9, _name: 'Magma', _saying: 'I'+ 'm a boss!' },
    { _id: 31, _name: 'Tornado' , _saying: 'I'+ 'm a boss!' },
    { _id: 21, _name: 'Dr Nice', _saying: 'I'+'m a boss!'},
    { _id: 22, _name: 'Narco', _saying: 'I'+ 'm a boss!' },
    { _id: 23, _name: 'Bombasto', _saying: 'I'+ 'm a boss!' },
    { _id: 24, _name: 'Celeritas' , _saying: 'I'+ 'm a boss!' },
    { _id: 25, _name: 'Magneta' , _saying: 'I'+ 'm a boss!'  },
    { _id: 26, _name: 'RubberMan' , _saying: 'I'+ 'm a boss!'},
    { _id: 27, _name: 'Dynama' , _saying: 'I'+ 'm a boss!' },
    { _id: 28, _name: 'Dr IQ' , _saying: 'I'+ 'm a boss!' },
    { _id: 29, _name: 'Magma', _saying: 'I'+ 'm a boss!' },
    { _id: 30, _name: 'Tornado' , _saying: 'I'+ 'm a boss!' }
];